### Post request to example server
POST http://localhost:8080/api/User/register
Content-Type: application/json
{
 String nombre,
      "email":"",
      "ciudad":"",
      "direccion":"",
      "password":"",
      "telefono":"",
      "userStatus":"",
      "rol":""
}
